-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.interactions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  fromUserId uuid NOT NULL,
  toUserId uuid NOT NULL,
  type text CHECK (type = ANY (ARRAY['INTERESTED'::text, 'REMOVED'::text])),
  timestamp bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT interactions_pkey PRIMARY KEY (id),
  CONSTRAINT interactions_fromUserId_fkey FOREIGN KEY (fromUserId) REFERENCES auth.users(id),
  CONSTRAINT interactions_toUserId_fkey FOREIGN KEY (toUserId) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  title text,
  name text,
  gender text CHECK (gender = ANY (ARRAY['Male'::text, 'Female'::text])),
  age integer,
  height text,
  weight text,
  skinColor text,
  bloodGroup text,
  diet text,
  bio text,
  caste text,
  gotra text,
  birthPlace text,
  birthTime text,
  nativeCountry text,
  nativeState text,
  nativeCity text,
  currentCountry text,
  currentState text,
  currentCity text,
  educationLevel text,
  educationStream text,
  educationDegree text,
  education text,
  occupation text,
  salary text,
  father jsonb DEFAULT '{}'::jsonb,
  mother jsonb DEFAULT '{}'::jsonb,
  paternalSide jsonb DEFAULT '{}'::jsonb,
  siblings jsonb DEFAULT '[]'::jsonb,
  healthIssues jsonb DEFAULT '[]'::jsonb,
  partnerAgeMin text,
  partnerAgeMax text,
  expectations jsonb DEFAULT '[]'::jsonb,
  email text UNIQUE,
  phone text,
  avatar_url text,
  is_demo boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  is_admin boolean DEFAULT false,
  is_hidden boolean DEFAULT false,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'admin'::text])),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);